const ADD_ITEM = 'ADD_ITEM'
const REMOVE_ITEM = 'REMOVE_ITEM'
const UNDO_ITEM = 'UNDO_ITEM'
const REDO_ITEM = 'REDO_ITEM'
const SET_FILTER = 'SET_FILTER'

module.exports = {
  ADD_ITEM,
  REMOVE_ITEM,
  UNDO_ITEM,
  REDO_ITEM,
  SET_FILTER
}
